services:
  - type: web
    name: rural-innovate-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://rural-innovate-backend.onrender.com