services:
  - type: web
    name: innovate-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://chandrahas1si22cs047_db_user:zgEzmi1JmL930GjU@cluster0.abxlwr9.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: your_super_secret_jwt_key_change_this_in_production_12345 